analyzer:
  errors:
    no_default_cases: ignore
    inference_failure_on_untyped_parameter: ignore   
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false