// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-KWPy1AMsecqIoLoHO5gJn-LQzERnnE',
    appId: '1:651753091974:web:e6671a228a5806aaf77207',
    messagingSenderId: '651753091974',
    projectId: 'smartcare-app-8a32a',
    authDomain: 'smartcare-app-8a32a.firebaseapp.com',
    storageBucket: 'smartcare-app-8a32a.firebasestorage.app',
    measurementId: 'G-67RN56CKNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBb13FLdOavcdl5aP1jIcSjE-YP_qmi1Q',
    appId: '1:651753091974:android:dfb4461688c23dcaf77207',
    messagingSenderId: '651753091974',
    projectId: 'smartcare-app-8a32a',
    storageBucket: 'smartcare-app-8a32a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvdox0IRdbp5PyJbS1quAd65hJSE0wsI',
    appId: '1:651753091974:ios:68b281404b79d43cf77207',
    messagingSenderId: '651753091974',
    projectId: 'smartcare-app-8a32a',
    storageBucket: 'smartcare-app-8a32a.firebasestorage.app',
    iosBundleId: 'com.graduation.smartcareAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvdox0IRdbp5PyJbS1quAd65hJSE0wsI',
    appId: '1:651753091974:ios:68b281404b79d43cf77207',
    messagingSenderId: '651753091974',
    projectId: 'smartcare-app-8a32a',
    storageBucket: 'smartcare-app-8a32a.firebasestorage.app',
    iosBundleId: 'com.graduation.smartcareAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-KWPy1AMsecqIoLoHO5gJn-LQzERnnE',
    appId: '1:651753091974:web:d64eb9899a61c8d5f77207',
    messagingSenderId: '651753091974',
    projectId: 'smartcare-app-8a32a',
    authDomain: 'smartcare-app-8a32a.firebaseapp.com',
    storageBucket: 'smartcare-app-8a32a.firebasestorage.app',
    measurementId: 'G-SQGS3K2D5R',
  );
}
