// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-jcw3g-5kN-_22oWG13fSMdPore1Vhg',
    appId: '1:563850624574:web:7d384b2ec8cc3b3328db6f',
    messagingSenderId: '563850624574',
    projectId: 'curai-app',
    authDomain: 'curai-app.firebaseapp.com',
    storageBucket: 'curai-app.firebasestorage.app',
    measurementId: 'G-8HKL6G0F7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQrVOX2t3PVQJfJCu3iTlRKEnrXPZT-Q',
    appId: '1:563850624574:android:ab67baf80482632a28db6f',
    messagingSenderId: '563850624574',
    projectId: 'curai-app',
    storageBucket: 'curai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIl318-0dl4J446S6-ceF2zOPPt9nroxo',
    appId: '1:563850624574:ios:fe41d2b3fad84ea028db6f',
    messagingSenderId: '563850624574',
    projectId: 'curai-app',
    storageBucket: 'curai-app.firebasestorage.app',
    iosBundleId: 'com.graduation.curaiAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIl318-0dl4J446S6-ceF2zOPPt9nroxo',
    appId: '1:563850624574:ios:fe41d2b3fad84ea028db6f',
    messagingSenderId: '563850624574',
    projectId: 'curai-app',
    storageBucket: 'curai-app.firebasestorage.app',
    iosBundleId: 'com.graduation.curaiAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs-jcw3g-5kN-_22oWG13fSMdPore1Vhg',
    appId: '1:563850624574:web:ea116452504a2f0628db6f',
    messagingSenderId: '563850624574',
    projectId: 'curai-app',
    authDomain: 'curai-app.firebaseapp.com',
    storageBucket: 'curai-app.firebasestorage.app',
    measurementId: 'G-SMLTHRXWEV',
  );
}
